name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build
        run: swift build

      - name: Test
        run: swift 

  SwiftLint:
    runs-on: ghcr.io/cirruslabs/macos-runner:sonoma
    steps:
      - uses: actions/checkout@v4
      - uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest
